services:
  watgbridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watgbridge
    volumes:
      - ./config.yaml:/go/src/watgbridge/config.yaml
      - ./gobot.sqlite.db:/go/src/watgbridge/gobot.sqlite.db
      - ./wawebstore.db:/go/src/watgbridge/wawebstore.db
    restart: unless-stopped
    environment:
      - GIT_USER_NAME=$(git config --global user.name)
      - GIT_USER_EMAIL=$(git config --global user.email)