name: Cache Nixpkg

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - state/version.txt
      - go.mod
      - go.sum
      - gomod2nix.toml
      - flake.nix
      - nix/packages/*.nix
  workflow_dispatch:

jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: watgbridge
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build --accept-flake-config -L .#packages.x86_64-linux.watgbridge
